export default {
  START_ASYNC_ACTION: "START_ASYNC_ACTION",
  SUCCESS_ASYNC_ACTION: 'SUCCESS_ASYNC_ACTION',
  CHOOSE_PROJECT: 'CHOOSE_PROJECT',
  CHOOSE_ORDER_LIST_TYPE: 'CHOOSE_ORDER_LIST_TYPE',
  COPY_TO_CLICKBOARD: 'COPY_TO_CLICKBOARD',
  RESET_CLICKBOARD: 'RESET_CLICKBOARD',
  TOGGLE_EDIT_MODE: 'TOGGLE_EDIT_MODE',

};
