export default {
  START_ASYNC_ACTION: 'START_ASYNC_ACTION',
  SUCCESS_ASYNC_ACTION: 'SUCCESS_ASYNC_ACTION',
  CHOOSE_PROJECT: 'CHOOSE_PROJECT',
  CHOOSE_ORDER_LIST_TYPE: 'CHOOSE_ORDER_LIST_TYPE',
  COPY_TO_CLICKBOARD: 'COPY_TO_CLICKBOARD',
  RESET_CLICKBOARD: 'RESET_CLICKBOARD',
  TOGGLE_EDIT_MODE: 'TOGGLE_EDIT_MODE',
  APPLY_EDIT_CHANGES: 'APPLY_EDIT_CHANGES',
  START_UPDATE_ORDER: 'START_UPDATE_ORDER',
  SUCCESS_UPDATE_ORDER: 'SUCCESS_UPDATE_ORDER',
  TOGGLE_DELETE_MODE: 'TOGGLE_DELETE_MODE',
  DELETE_ORDER: 'DELETE_ORDER',
};
